export const fallbackEmail = "rifqyaliansyah@gmail.com";

export const fallbackSkills = [
  "React / Next.js",
  "TypeScript",
  "Figma",
  "Node.js",
  "Tailwind CSS",
];

export const fallbackHeroPreviewImages = [
  { src: "/example.jpg", alt: "Frontend Specialist Certificate" },
  { src: "/example.jpg", alt: "UI/UX Design Mastery Certificate" },
  { src: "/example.jpg", alt: "React & Next.js Advanced Certificate" },
  { src: "/example.jpg", alt: "Cloud Practitioner Certificate" },
  { src: "/example.jpg", alt: "Fullstack Engineering Certificate" },
  { src: "/example.jpg", alt: "Mobile App Development Certificate" },
];

export const fallbackTestimonials = [
  {
    id: "1",
    quote: "Rifqy selalu bisa nerjemahin requirement yang ambigu jadi UI yang rapi dan gampang dipakai.",
    name: "Dimas Pratama",
    role: "Product Manager",
    avatar: null,
  },
  {
    id: "2",
    quote: "Kerja bareng Rifqy enak banget, komunikasinya jelas dan hasilnya selalu di atas ekspektasi.",
    name: "Sarah Amelia",
    role: "UI/UX Designer",
    avatar: null,
  },
  {
    id: "3",
    quote: "Detail banget soal micro-interaction, portofolionya juga mencerminkan itu.",
    name: "Bagas Nugraha",
    role: "Frontend Lead",
    avatar: null,
  },
];

export const fallbackProjects = [
  {
    _id: "1",
    id: "1",
    title: "E-commerce Redesign",
    slug: { current: "ecommerce-redesign" },
    description: "A complete overhaul of the user experience for a leading e-commerce platform.",
    coverImage: undefined,
    imageSrc: "/example.jpg",
    gallery: [
      { src: "/example.jpg", alt: "E-commerce Redesign Overview" },
      { src: "/example.jpg", alt: "Checkout Experience" },
      { src: "/example.jpg", alt: "Product Detail View" },
      { src: "/example.jpg", alt: "Mobile Responsive Layout" },
    ],
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "Stripe"],
    projectUrl: "https://example.com",
    githubUrl: "https://github.com",
    publishedAt: "2024-05-10",
    href: "/projects/ecommerce-redesign",
  },
  {
    _id: "2",
    id: "2",
    title: "Fintech Mobile App",
    slug: { current: "fintech-mobile-app" },
    description: "Designing a seamless banking experience for the new generation with biometric security and instant transfers.",
    coverImage: undefined,
    imageSrc: "/example.jpg",
    gallery: [
      { src: "/example.jpg", alt: "Fintech Dashboard" },
      { src: "/example.jpg", alt: "Biometric Auth Screen" },
      { src: "/example.jpg", alt: "Transaction Analytics" },
    ],
    tags: ["React Native", "TypeScript", "Node.js", "GraphQL"],
    projectUrl: "https://example.com",
    githubUrl: "https://github.com",
    publishedAt: "2024-03-15",
    href: "/projects/fintech-mobile-app",
  },
  {
    _id: "3",
    id: "3",
    title: "Healthcare Dashboard",
    slug: { current: "healthcare-dashboard" },
    description: "Simplifying complex medical data into intuitive visual interfaces for practitioners and hospital staff.",
    coverImage: undefined,
    imageSrc: "/example.jpg",
    gallery: [
      { src: "/example.jpg", alt: "Healthcare Analytics" },
      { src: "/example.jpg", alt: "Patient Vital Monitoring" },
    ],
    tags: ["React", "D3.js", "Tailwind CSS", "Python"],
    projectUrl: "https://example.com",
    githubUrl: "https://github.com",
    publishedAt: "2023-11-20",
    href: "/projects/healthcare-dashboard",
  },
  {
    _id: "4",
    id: "4",
    title: "Real Estate Platform",
    slug: { current: "real-estate-platform" },
    description: "Connecting buyers and sellers through an immersive property search and virtual tour experience.",
    coverImage: undefined,
    imageSrc: "/example.jpg",
    gallery: [
      { src: "/example.jpg", alt: "Property Search Map" },
      { src: "/example.jpg", alt: "Virtual Tour View" },
    ],
    tags: ["Next.js", "Mapbox", "Prisma", "PostgreSQL"],
    projectUrl: "https://example.com",
    githubUrl: "https://github.com",
    publishedAt: "2023-08-14",
    href: "/projects/real-estate-platform",
  },
  {
    _id: "5",
    id: "5",
    title: "Travel Booking Site",
    slug: { current: "travel-booking-site" },
    description: "A sleek and modern interface for booking flights and accommodations with real-time price tracking.",
    coverImage: undefined,
    imageSrc: "/example.jpg",
    gallery: [
      { src: "/example.jpg", alt: "Flight Booking Interface" },
      { src: "/example.jpg", alt: "Hotel Booking Details" },
    ],
    tags: ["Next.js", "Framer Motion", "Tailwind CSS"],
    projectUrl: "https://example.com",
    githubUrl: "https://github.com",
    publishedAt: "2023-04-10",
    href: "/projects/travel-booking-site",
  },
  {
    _id: "6",
    id: "6",
    title: "AI Productivity Suite",
    slug: { current: "ai-productivity-suite" },
    description: "An integrated workspace powered by AI to supercharge daily workflows and summarize complex meetings.",
    coverImage: undefined,
    imageSrc: "/example.jpg",
    gallery: [
      { src: "/example.jpg", alt: "AI Editor Canvas" },
      { src: "/example.jpg", alt: "Meeting Summary Feed" },
    ],
    tags: ["Next.js", "OpenAI API", "Tailwind CSS", "Supabase"],
    projectUrl: "https://example.com",
    githubUrl: "https://github.com",
    publishedAt: "2024-01-08",
    href: "/projects/ai-productivity-suite",
  },
];

export const fallbackWritings = [
  {
    _id: "1",
    id: "1",
    title: "The Future of UI Design in 2026",
    slug: { current: "future-of-ui-design-2026" },
    description: "Exploring upcoming trends in user interface design, generative micro-interactions, and how to prepare for them.",
    excerpt: "Exploring upcoming trends in user interface design, generative micro-interactions, and how to prepare for them.",
    coverImage: undefined,
    imageSrc: "/example.jpg",
    publishedAt: "2026-08-15",
    readingTime: "5 min read",
    tags: ["UI/UX", "Design Systems", "Trends"],
    href: "/writings/future-of-ui-design-2026",
  },
  {
    _id: "2",
    id: "2",
    title: "Building Accessible Web Applications",
    slug: { current: "building-accessible-web-applications" },
    description: "A comprehensive guide to ensuring your web apps are usable and delightful for everyone with WCAG guidelines.",
    excerpt: "A comprehensive guide to ensuring your web apps are usable and delightful for everyone with WCAG guidelines.",
    coverImage: undefined,
    imageSrc: "/example.jpg",
    publishedAt: "2026-06-20",
    readingTime: "8 min read",
    tags: ["Accessibility", "Frontend", "HTML5"],
    href: "/writings/building-accessible-web-applications",
  },
  {
    _id: "3",
    id: "3",
    title: "Mastering Micro-interactions with Framer Motion",
    slug: { current: "mastering-micro-interactions" },
    description: "How intentional spring physics and subtle animations elevate perceived software quality.",
    excerpt: "How intentional spring physics and subtle animations elevate perceived software quality.",
    coverImage: undefined,
    imageSrc: "/example.jpg",
    publishedAt: "2026-04-05",
    readingTime: "6 min read",
    tags: ["Framer Motion", "Animation", "React"],
    href: "/writings/mastering-micro-interactions",
  },
];

export const fallbackHighlights = [
  { iconName: "briefcase", label: "5+ Years of Experience" },
  { iconName: "map-pin", label: "Based in Indonesia" },
  { iconName: "send", label: "Open to freelance & collaborations" },
];

export const defaultSocialLinks = [
  { platform: "x", href: "https://x.com/", label: "X (Twitter)" },
  { platform: "instagram", href: "https://instagram.com/", label: "Instagram" },
  { platform: "threads", href: "https://threads.net/", label: "Threads" },
  { platform: "linkedin", href: "https://linkedin.com/", label: "LinkedIn" },
  { platform: "youtube", href: "https://youtube.com/", label: "YouTube" },
];
